const VARIANTS = [
  {
    name: "Cypress 6",
    path: "cypress-6",
    version: "6",
    typescript: false,
    skippable: true,
    copyPlugin: true,
  },
  {
    name: "Cypress 7",
    path: "cypress-7",
    version: "7",
    typescript: false,
    skippable: true,
    copyPlugin: true,
  },
  {
    name: "Cypress 8",
    path: "cypress-8",
    version: "8",
    typescript: false,
    skippable: false,
    pluginFile: "preprocessor-babel-config",
    copyPlugin: true,
  },
  {
    name: "Cypress 9",
    path: "cypress-9",
    version: "9",
    typescript: false,
    skippable: false,
    pluginFile: "preprocessor-babel-config",
    copyPlugin: true,
  },
  {
    name: "Cypress 10",
    path: "cypress-10",
    version: "10",
    isLatest: true,
    typescript: false,
    skippable: false,
    configFile: "cypress.config.js",
    supportFile: "e2e.js",
    copyPlugin: false,
  },
  {
    name: "TypeScript",
    path: "typescript",
    version: "ts",
    skippable: true,
    typescript: true,
  },
];

module.exports = VARIANTS;
