name: test-e2e
on:
  push:
    branches:
      - master
      - release
  pull_request:
concurrency:  
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Test E2E
        run: pnpm run test:e2e
