name: test-mutation
on:
  push:
    branches:
      - main
      - release
  pull_request:
  workflow_dispatch:
concurrency:  
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-mutation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.4.0
    - name: Install pnpm
      uses: pnpm/action-setup@v4.4.0
    - uses: actions/setup-node@v4.4.0
      with:
        node-version: '22.23.2'
        registry-url: 'https://registry.npmjs.org/'
    - name: Install dependencies
      run: pnpm install
    - name: Test mutation
      run: pnpm run test:mutation
      env:
        STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_TOKEN }}
    - name: Upload test mutation report for elements
      uses: actions/upload-artifact@v4.6.2
      with:
        name: report-test-mutation
        path: reports/mutation
        retention-days: 1
